import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Provider from './Provider';
import NavBar from './_components/NavBar';
import MonitorSession from './_components/MonitorSession';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'e2e test',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <NavBar />
          <MonitorSession />
          {children}
        </Provider>
      </body>
    </html>
  );
}
